### ISSUE TITLE
Not adding inputtypes class

### ISSUE THREAD

**Issue by Dan503** [Modernizr/customizr#45] opened 2017-03-28 01:02 UTC
I wanted to use the inputtypes test in my project

https://modernizr.com/download?setclasses&q=inputtypes

Customizr was able to pick up on the fact that I used the rules in in the project and the JS rule `Modernizr.inputtypes.range` is working from the generated js file just fine.

The generated code did not add the `inputtypes` class to the html element though even though all of the other tests are getting added

`````
<html class="js flexbox flexwrap svg csspointerevents backgroundblendmode objectfit object-fit csstransforms js js-loaded" lang="en">
`````

This also seems to be the case for the `input` modernizr test https://modernizr.com/download?setclasses&q=input

**Comment by jimjimovich** [comment] 2017-12-04 22:11
Yes, this is either a bug or at the very least, the documentation needs to be updated to show that the inputtypes class is no longer added.

**Comment by rejas** [comment] 2018-06-09 09:07
This seems to be a bug in Modernizr and not in customizr. 

The issue is already tracked I think in https://github.com/Modernizr/Modernizr/issues/2130

**Comment by rejas** [comment] 2018-06-09 11:17
Same issue with the test for input, adds a js object for it but doesnt add any css classes to the html-tag. Or is there some intention behind it @patrickkettner ?

**Comment by patrickkettner** [comment] 2018-06-09 17:06
dont believe its intentional. As it is an upstream issue like @rejas said, closing this one in favor of it

**Closed by patrickkettner** 2018-06-09 17:06 UTC
